version: '3'
services:
  eureka-server:
    image: eureka:0.1
    ports:
      - 8761:8761

  auth-server:
    image: auth:0.1
    ports:
      - 8100:8100
    links:
      - eureka-server

  user-server:
    image: userserver:0.1
    ports:
      - 8089:8089
    links:
      - eureka-server

  admin-server:
    image: adminserver:0.1
    ports:
      - 8099:8099
    links:
      - eureka-server

  gatway:
    image: gateway:0.1
    ports:
      - 9001:9001
    links:
      - eureka-server
      - auth-server
      - user-server
      - admin-server