# Build image for java runtime enviroment
FROM openjdk:8-jre 

# Work in current dir
WORKDIR /

#COPY jar into container
ADD auth-server-0.0.1-SNAPSHOT.jar auth.jar

#Expose container's port
EXPOSE 8100

#Start up 
CMD java -jar auth.jar