# Build image for java runtime enviroment
FROM openjdk:8-jre 

# Work in current dir
WORKDIR /

#COPY jar into container
ADD gateway-server-0.0.1-SNAPSHOT.jar gateway.jar

#Expose container's port
EXPOSE 9001

#Start up 
CMD java -jar gateway.jar