spring:
  application:
    name: gateway
server:
  port: 9001
ribbon:
  eureka:
    enable: false
  ReadTimeout: 30000
  ConnectionTimeout: 30000
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true
zuul:
  routes:
    admin-server: /admin/**
    user-server: /**
  ignored-patterns:
    -/admin-server/**
    -/auth-server/**
feign:
  httpclient:
    connection-timeout: 30000